version: '3'

services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/src/media
    depends_on:
      - redis
  celery:
    build: .
    command: celery worker -A image_parroter --loglevel=info
    volumes:
      - ./media:/src/media
    depends_on:
      - redis